// Presentation-layer geographic coordinates for the Countries globe.
//
// IMPORTANT: this lives here — NOT in content/data/countries.json — on purpose.
// countries.json is a synced snapshot regenerated by scripts/sync-airtable.js,
// which only writes a fixed field set. Any lat/lon added there would be wiped on
// the next `npm run sync`. Airtable has no coordinate fields, and placing a dot
// on a globe is a display concern, so the mapping lives in the app layer, keyed
// by the country `slug` (the stable join key used across content/data).
//
// Coordinates are representative points (national centroid or the relevant
// coastal/lake region for the fisheries work), not precise capitals. Regional or
// cross-cutting entries that have no single point on a globe (e.g. "Global") are
// intentionally omitted — they render in the list below the map, not as a marker.

const COUNTRY_COORDINATES = {
    'timor-leste': { lat: -8.8, lon: 125.7 },
    kenya: { lat: -0.5, lon: 37.9 },
    zanzibar: { lat: -6.16, lon: 39.2 },
    mozambique: { lat: -18.0, lon: 35.5 },
    malawi: { lat: -13.25, lon: 34.4 },
    zambia: { lat: -14.0, lon: 27.8 },
    nigeria: { lat: 9.08, lon: 8.68 },
    ghana: { lat: 7.95, lon: -1.02 },
    eritrea: { lat: 15.3, lon: 38.9 },
    namibia: { lat: -22.0, lon: 17.1 },
    malaysia: { lat: 3.5, lon: 102.2 },
    'solomon-islands': { lat: -9.64, lon: 160.16 },
    guatemala: { lat: 15.5, lon: -90.3 },
    colombia: { lat: 4.6, lon: -74.1 },
    // West Africa / CAOPA — regional network; placed on the Senegal coast, the
    // hub of the CAOPA confederation.
    'west-africa-caopa': { lat: 14.5, lon: -15.5 },
};

/** Coordinates for a country slug, or null when the entity has no single map point. */
export function getCountryCoordinates(slug) {
    return COUNTRY_COORDINATES[slug] || null;
}
